export enum EActionKey {
  RESTORE_EVENTS = 'CALENDAR/RESTORE_EVENTS',
  SET_EVENTS = 'CALENDAR/SET_EVENTS',
  ADD_EVENT = 'CALENDAR/ADD_EVENT',
  EDIT_EVENT = 'CALENDAR/EDIT_EVENT',
  DELETE_EVENT = 'CALENDAR/DELETE_EVENT',
  LOGIN_SUCCESS = 'AUTH/LOGIN_SUCCESS',
  LOGOUT_SUCCESS = 'AUTH/LOGOUT_SUCCESS'
}

export enum EAuthState {
  ANONYMOUS = 'ANONYMOUS',
  LOGGED_IN = 'LOGGED_IN',
  AWAITING_AUTH_RESPONSE = 'AWAITING_AUTH_RESPONSE'
}
